import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import CopyRight from "@/components/CopyRight";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Lwskart",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <Navbar />
        {children}
        <Footer />
        <CopyRight />
      </body>
    </html>
  );
}
